### ISSUE TITLE
[Bug] Game crash upon startup

### ISSUE THREAD

**Issue by daniel-zh23** [PinkGoosik/visuality#19]
Hi. I am using fabric loader 0.14.8-1.19 and the crash crash every single time when i start it. I removed all the mods except the fabric api 0.56.1+1.19, but still crashes.
Mods i use and the crash log are attached.
![image](https://user-images.githubusercontent.com/88737326/175279846-eb8fb9d9-8c48-4cee-b915-d52b731a185d.png)
[crash-2022-06-23_13.23.42-client.txt](https://github.com/PinkGoosik/visuality/files/8966435/crash-2022-06-23_13.23.42-client.txt)

**Comment by PinkGoosik** [comment]
Install cloth config https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by daniel-zh23** [comment]
It works now. Thank you. (Quick suggestion) Update the required dependencies in https://modrinth.com/mod/visuality.

**Comment by PinkGoosik** [comment]
It suppose to be optional so needs to be fixed

**Comment by Lisici4** [comment]
still crashes even with a cloth config
![image](https://user-images.githubusercontent.com/109102767/178330092-3925a0c3-0183-454e-9188-b754d4216b12.png)
[crash-log.txt](https://github.com/PinkGoosik/visuality/files/9086530/crash-log.txt)
