### ISSUE TITLE
TLCosmetica's Update Checker wastes time on the Main Thread

### ISSUE THREAD

**Issue by StockiesLad** [PinkGoosik/visuality#24]
Please change this
![image](https://user-images.githubusercontent.com/60066663/192804336-138a061d-ad47-4da9-934e-4dffb811ca1d.png)

**Comment by PinkGoosik** [comment]
update visuality

**Comment by PinkGoosik** [comment]
to 0.3.4 if you're on 1.17.1, 0.4.3 for 1.18.2 or 0.5.1 for 1.19.2

**Comment by StockiesLad** [comment]
Ok
