### ISSUE TITLE
does not detect fabric api and crashes?

### ISSUE THREAD

**Issue by slovinsqui** [PinkGoosik/visuality#31]
visuality 0.5.3 cant startup minecraft 1.19 (fabric 0.14.10)

Minecraft tells me I don´t have any version of fabric api installed, when I DO have it installed, preventing me to start the game

Log:

[latest.log](https://github.com/PinkGoosik/visuality/files/9986844/latest.log)

fabric "Incompatible mod set" report:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, any version.
Unmet dependency listing:
	 - Mod 'Visuality' (visuality) 0.5.3 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by slovinsqui** [comment]
when rolling back to visuality 0.5.2, it keeps preventing me from opening minecraft, asking me to install fabric

**Comment by slovinsqui** [comment]
just tested
does not happen in visuality 0.5.1

**Comment by PinkGoosik** [comment]
what version of fabric api do you have?

**Comment by PinkGoosik** [comment]
it seems like your fabric api still has id `fabric` instead of `fabric-api`, try to update to a newer version of fabric api

**Comment by slovinsqui** [comment]
so I updated fabric api in the versions tab from curseforge app, but that version only works for 1.19.1, a version where some of the mods from my modpack have not been ported yet
so maybe it´s best to not update?

**Comment by PinkGoosik** [comment]
yeah 0.5.2+ doesn't have any important changes
